[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    bogde/HX711@^0.7.4

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DLV_FONT_MONTSERRAT_12=1
    -DLV_FONT_MONTSERRAT_14=1 
    -DLV_FONT_MONTSERRAT_16=1
    
    ; --- TFT_eSPI 设置 ---
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER=1
    -DST7735_GREENTAB2=1
    
    -DTFT_WIDTH=160
    -DTFT_HEIGHT=128
    
    ; 引脚设置
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=15
    -DTFT_RST=14
    
    ; 字体和SPI设置
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=27000000